//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.ExamTakens = new HashSet<ExamTaken>();
        }
    
        public int ExamID { get; set; }
        public int ExaminerID { get; set; }
        public System.TimeSpan ExamMaxDuration { get; set; }
        public int MaxAllowedAttemptsPerPerson { get; set; }
        public System.DateTime ExamStartDate { get; set; }
        public System.TimeSpan ExamStartTime { get; set; }
        public System.DateTime ExamEndDate { get; set; }
        public System.TimeSpan ExamEndTime { get; set; }

        public virtual ExamAdministrator ExamAdministrator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamTaken> ExamTakens { get; set; }
    }
}
