//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTaken
    {
        public int ExamID { get; set; }
        public int ExamineeID { get; set; }
        public int RecordingID { get; set; }
        public int LocationID { get; set; }
        public System.DateTime SubmissionTime { get; set; }
        public double Score { get; set; }
        public double ConfidenceScore { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Examinee Examinee { get; set; }
    }
}
